### ISSUE TITLE
LINUX / Register: job survey has no description in docs or job template

### ISSUE THREAD

**Issue by benblasco** [RedHatGov/product-demos#29]
Referring to the LINUX / Register job here:

https://github.com/RedHatGov/product-demos/blob/main/linux/README.md

There's a survey to run but neither the instructions nor the survey definition have helpful descriptions

![image](https://user-images.githubusercontent.com/42140583/197662206-68a62e20-87d7-485b-8101-31e969bd2380.png)

1. Explain we can use wildcards for server name or pattern
2. What's the environment?  What's the impact of my choice?
3. What's an Ansible group.  it's a free text field but where does it tag the hosts?  In insights? Elsewhere?

**Comment by willtome** [comment]
Are you suggesting more info in the survey itself or just in the docs?

**Comment by benblasco** [comment]
PR contains updates the survey description as well as the suggested usage.

**Comment by benblasco** [comment]
Note: PR does not contain updated screenshot.
