### ISSUE TITLE
LINUX - Temporary Sudo: template shouldn't require latest "at" package

### ISSUE THREAD

**Issue by benblasco** [RedHatGov/product-demos#31]
This playbook tries to install the latest "at" package when all it needs is to ensure that "at" is already installed and running

https://github.com/RedHatGov/product-demos/blob/main/linux/temp_sudo.yml

Proposed change: s/latest/present

I can fix this and will log a PR

**Comment by willtome** [comment]
what if at isn't installed?

**Comment by benblasco** [comment]
PR should fix issue
