### ISSUE TITLE
LINUX / Patching: Should the patching job run insights-client when finished?

### ISSUE THREAD

**Issue by benblasco** [RedHatGov/product-demos#32]
Title says it all.... But maybe there needs to be a conditional associated with this for the case where the user hasn't connected the systems to Insights using LINUX / Register.

Thoughts?

**Comment by willtome** [comment]
maybe? is that the only way insights knows if a system is updated?

**Comment by benblasco** [comment]
Insights will only pick up changes when you run the insights-client, so we either want the results immediately (as per this issue) or we just wait until the next job run some time in the next 24 hours.

**Comment by benblasco** [comment]
Note to self: Will need to build logic into this to either a) ignore failed insights-client runs or b) only run when the insights-client is registered

**Comment by willtome** [comment]
Closing. #48 has been merged
