### ISSUE TITLE
LINUX / Run Shell Script: Does not show output

### ISSUE THREAD

**Issue by benblasco** [RedHatGov/product-demos#33]
Two related issues
- This command does not show the output of the shell script execution?
- In the suggested usage the example provided is an arbitrary command rather than a shell script, see here: https://github.com/RedHatGov/product-demos/blob/main/linux/README.md.  The example given is "Example usage would be getting the public key used in the environment with the command `cat .ssh/authorized_keys`".  Can we run arbitrary commands?

**Comment by willtome** [comment]
What output do you want to see and why? If you click on the task you can see stdout. This is a horrible practice but it shows that we can run existing automation plus gives you a way to do useful thing in a demo like get the public key that you need for setting up cloud demos.

**Comment by benblasco** [comment]
Added printout of stdout_lines so you can follow what's going on.
