### ISSUE TITLE
LINUX / Fact Scan: Survey inconsistent with other templates

### ISSUE THREAD

**Issue by benblasco** [RedHatGov/product-demos#35]
This particular survey, when launched, prompts for "Limit", whereas the other jobs prompt for "Server Name or Pattern", which is arguably more informative.  Minor cosmetic issue, so low priority,

**Comment by willtome** [comment]
This is because it uses a different repo which we don't have control over. This could be mirrored over to this repo and then the UX could match the rest of the lab. Great suggestions but I agree, low priority.

**Comment by benblasco** [comment]
Easier long term for us to improve the description in "suggested use" than to fork/mirror.  will PR pending outcome of #34
