### ISSUE TITLE
create_infra.yml seems broken

### ISSUE THREAD

**Issue by vikingcowboy86** [RedHatGov/product-demos#38]
I tried to run this to create a VPC and kept running into errors during the playbook run. Rewrote the playbook, introduced fresh vars and survey to correlate and worked just fine! Here is the YAML file i used. For the survey, i just did:

VPC Name: <text>
CIDR: <text>
Region: *multiple choice* (us-east-1, us-east-2)

Let me know what you think

---
- name: Create AWS VPC
  hosts: localhost
  gather_facts: false
  vars:
    name: undef
    cidr: undef
    aws_region:
    - us-east-1
    - us-east-2
  tasks:

  - name: Create VPC
    amazon.aws.ec2_vpc_net:
      name: "{{ name }}"
      cidr_block: "{{ cidr }}"
      region: "{{ aws_region }}"

**Comment by vikingcowboy86** [comment]
https://github.com/vikingcowboy86/product-demos/blob/main/cloud/aws.create.vpc.yml

**Comment by willtome** [comment]
I was unable to reproduce this issue
