### ISSUE TITLE
install packages on the RHEL machines (for RHEL Patching)

### ISSUE THREAD

**Issue by HichamMourad** [RedHatGov/product-demos#62]
We need to make sure that the RHEL machines have the following packages. Some RHEL images on some clouds may not have these.

dnf install -y yum-utils bind-utils subscription-manager

**Comment by willtome** [comment]
Adding a dnf install for `yum-utils` to patching and `subscription-manager` to register should do the trick

**Comment by willtome** [comment]
Resolved by PR #63
